### ISSUE TITLE
-deletekey does not work

### ISSUE THREAD

**Issue by vyachkonovalov** [andreimarcu/linx-client#16]
linx-client version 1.5.1

`linx-client -d https://linx.example.com/myphoto.jpg -deletekey mysecret`
returns
> No delete key for https://linx.example.com/myphoto.jpg

no matter what

**Comment by 132ikl** [comment]
I cannot reproduce this issue

**Comment by vyachkonovalov** [comment]
Sorry, I misread the docs. `-deletekey` is for file upload, not for deletion 🤦‍♂️
