### ISSUE TITLE
Build fails due to bitbucket.org/tshannon/config dependency

### ISSUE THREAD

**Issue by kris7t** [andreimarcu/linx-client#17]
Since BitBucket remove support for Mercurial repositories, the https://bitbucket.org/tshannon/config repository was deleted. Hence, it is not possible to build `linx-client` any more, because `go` cannot dowload the `config` dependency from there:

```
package bitbucket.org/tshannon/config: reading https://api.bitbucket.org/2.0/repositories/tshannon/config?fields=scm: 403 Forbidden
        server response: Repository currently not available.
```

**Comment by andreimarcu** [comment]
Thanks for reporting this!
